version: 2
project_name: metacore-kernel

before:
  hooks:
    - go mod tidy
    - go test -race ./...

builds:
  - skip: true

archives:
  - format: source

release:
  draft: false
  prerelease: auto

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
  groups:
    - title: "New features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: "Other"
      order: 999
